server:
  port: 9004
spring:
  application:
    name: consul-user-service
  #    name: user-service
#  zipkin: # 设置zipkin-server访问地址
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 0.1 # 设置Sleuth的抽样收集概率
  cloud: # 添加consul地址
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}